flowchart TD
  %% Name settings
  _setup(_setup: file)
  initial(initial: function)
  first(first: function)
  rest(rest: function)
  last(last: function)

  %% Hyperlink settings
  click _setup "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/_setup.js"
  click initial "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/initial.js"
  click first "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/first.js"
  click rest "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/rest.js"
  click last "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/last.js"

  %% Array settings
  _setup --> initial
  _setup --> rest
  initial --> first
  rest --> last