flowchart TD
  %% Name settings
  _setup(_setup: file)
  initial(initial: function)
  first(first: function)

  %% Hyperlink settings
  click _setup "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/_setup.js"
  click initial "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/initial.js"
  click first "https://github.com/AshGreyG/To-Realize-Underscore/blob/main/modules/first.js"

  %% Array settings
  _setup --> initial
  initial --> first